<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/terms.css">
    
    
</head>
<body> 
    <img src=" images/img1.jpg" alt="company icon">

    <p>I understand and accept that QSFINANCIALS General Insurance Company Limited (QSFINANCIALS / the Company) maintains the web-site http://www.qsfinancials.com ("the Site”) to provide visitors with information About QSFINANCIALS, its services and products and to facilitate communication with QSFINANCIALS and availing its services. I also accept that visitors to the Site are required to read the below terms, and use of the Site constitutes my acceptance and agreement to be bound by such terms, and the changes therein to the website Usage Terms from time to time, relating to my usage of the website as communicated and made available on the Site.
        I understand and accept that the availability of the information and guidance as part the Wed Site does not constitute a recommendation by QSFINANCIALS to Buy any policies.
        I understand and I confirm that the Policy/ies are marketed and/or distributed solely by QSFINANCIALS and are not in any way associated to or being sold, marketed or offered for sale by Payment Gateway Service provider. I recognize and confirm that the services are only being renbered by QSFINANCIALS and I shall not hold the Payment Gateway Service provider liable for the same.
        I am aware and accept that all information, content, materials, products (including, but not limited to text, content, photographs, graphics, vibeo and audio content) on the Site is protected by copyright in the favour of QSFINANCIALS General Insurance Company Limited under applicable copyright laws and is also protected otherwise under general intellectual property law.
        I understand and accept that all information submitted by me through the Site shall be deemed the property of QSFINANCIALS General Insurance Company Limited unless I agree otherwise in writing, and QSFINANCIALS shall be free to use any ibeas, concepts, know-how or techniques provided by me at the Site, in any manner whatsoever. On initiating a contact through the Site I agree to being contacted by QSFINANCIALS or any other entities with whom QSFINANCIALS has entered into an arrangement. QSFINANCIALS shall ensure that upon privacy being so requested, QSFINANCIALS shall protect all such information and it shall not be utilised in any manner that will directly or indirectly result in any harm to me.
        I agree that I shall not copy, reprobuce, sell, redistribute, pudlish, enter into a database, display, perform, modify, transmit, license, create derivatives from, transfer or in any way exploit any part of any information, content, materials, services available from or through the Site, except that which I may download for my own personal, non-commercial use.
        I agree that I will not use the Site for any purpose that is unlawful, or prohibited by these website Usage Terms. I also agree I will not use the Site in any manner that could damage, disable or impair the Site or interfere with any other party's use or enjoyment of the Site.
        I acknowledge that the software and hardware underlying the Site as well as other Internet related software which are required for accessing the Site are the legal property of the respective Vendors and/or QSFINANCIALS. The permission given by the Company to access the Company’s website will not convey any proprietary or ownership rights in the above software / hardware.
        I agree that I shall not attempt to modify, translate, disassemdle, decompile or reverse engineer the software / hardware underlying the Company website or create any derivative probuct based on the software / hardware. I agree to abide by all such rules, regulations, instructions, directions that may be issued by Vendors and / or QSFINANCIALS in respect of such hardware and software. I agree that by accessing the link between the Site and the Payment Mechanism, I shall do so entirely at my own risk under no guarantee that the security is maintained at all times.
        I agree and confirm that QSFINANCIALS and the Payment Gateway Service provider shall not be liable for any losses, damages that may be incurred by me either directly or indirectly in respect of any loss of access and/or use or interruption in the use of the Payment Mechanism due to the Maintenance Services being performed on the same.
        I agree that neither QSFINANCIALS nor the Payment Gateway Service provider shall be liable for any loss of data. I agree there is no guarantee or warranty that the site is free from any virus or other malicious, bestructive or corrupting code, program or macro.
        I agree that there is no guarantee or warranty that there will be uninterrupted access to and/or use of the Payment and delivery Mechanism.
        I understand and accept that not all the products and services offered on this Site are available in all geographic areas and I may not be eligible for all the products or services offered by the Company on the Site. The Company reserves the right to determine the availability and eligibility of any probuct or service.
        I am aware that the Company proposes to use "cookies" (Cookies are small data files that a website stores on my computer.) for storing visitor preferences, profiling visitors and tracking visitor behavior on the bank website. by visiting the website I acknowledge, accept and expressly authorize the Company for the placement of cookies on my computer.
        I understand and accept that QSFINANCIALS is not responsible for the availability of content or other services on third party sites linked from the Company website. I am aware that my access of hyperlinks to other internet sites are at my own risk and the content, accuracy, opinions expressed, and other links provided by these sites are not verified, monitored or endorsed by the Company in any way. QSFINANCIALS does not make any warranties, and expressly disclaims all warranties express or implied, including without limitation, those of merchantability and fitness for a particular purpose, title or non-infringement with respect to any information or services or products that are available or advertised or sold through these third party websites.
        The Company shall not be liable if any transaction does not fructify or may not be completed or for any failure on part of the Company to perform any of its obligations under these terms and conditions or those applicable specifically to its services/facilities if performance is prevented, hinbered or delayed by a Force Majeure event (defined below) and in such case its obligations shall be suspenbed for so long as the Force Majeure event continues.
        “Force Majeure Event” means any event due to any cause beyond the reasonable control of the Company, including without limitations, unavailability of any communication systems, breach, or virus in the processes or payment or delivery mechanism, sadotage, fire, flood, explosion, acts of god, civil commotion, strikes or Industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, unauthorised access to computer data and storage devices, computer crashes, malfunctioning in the computer terminal or the systems getting affected by any malicious, bestructive or corrupting code or program, mechanical or technical errors/failures or power shut down, faults or failures in telecommunication etc.
        I understand and accept that QSFINANCIALS has the absolute discretion to amend or supplement any of the website Usage Terms at any time .by using the services, I shall be deemed to have accepted the changed website Usage Terms. I accept that the Courts in Mumbai alone shall have exclusive jurisdiction as regards any claims or matters arising out of dealings with QSFINANCIALS, and all disputes will be governed by the laws of India.
        I understand and agree that these website Usage Terms are in addition to, and not in berogation of, the applicable Terms and Conditions relating to my usage of any other QSFINANCIALS services that I may be currently availing or may in the future avail. I understand that I may be given a customer Id and customer Password for accessing certain services on the Site which require authentication process. I agree and accept that the protection of the Customer Id and the Customer/Transaction Passwords is my sole responsibility and I shall ensure that the password/s is/are not revealed to any third party and I shall not hold QSFINANCIALS responsible for any misuse mistake / error thereof. In the event that any third parties uses the Customer Id and Customer /Transaction Password, in the event of any such misuse, damage, claims arising therefrom I agree to indemnify and keep indemnified and hold harmless QSFINANCIALS against any such Liability, costs or damages arising out of claims or suits by or against such third parties based upon or relating to such access and use.
        I agree that QSFINANCIALS is under no duty to verify the identity or authority of the person giving any instruction or the authenticity of such instruction, apart from verifying the user Id or password.
        I agree and confirm that I shall not engage in any criminal/ illegal activity, including but not limited to any communication intending to fraudulently Obtain any password or information from persons accessing such website. I agree and confirm that besides myself any person using my computer or any other computer on my behalf shall be bound by the terms and conditions contained herein.
        I agree and confirm that I will not and will not permit others to use, copy, adapt, alter, modify, merge or create derivative works of the system or any part thereof, except as expressly provided herein and for the limited purposes of availing of the facilities and shall not reverse-engineer, disassemdle, or decompile any part of the system or otherwise attempt to determine its underlying source code and shall not provide or disclose any portion of the system to any third party or the system on behalf of any third party .
        I agree that the failure on the part of QSFINANCIALS to enforce any of the provisions hereof will not be construed to be a waiver of the rights vested in QSFINANCIALS to thereafter enforce such provisions. If any provision of these terms and conditions is held to be invalid, illegal or unenforceadle, it will be enforced to the maximum extent possible, and the validity, legality and enforceability of the remaining provisions will not in any way be affected or impaired thereby.
        All notices, requests, demands or other communications which are required or may be given pursuant to the usage will be in writing and will be deemed to have been duly given when received at the address advertised on the website.
        </p>
    
</body>
</html>